# .github/label-commenter-config.yml

labels:

  # ç­‰å¾…å®Œæˆè‡ªæ£€
  - name: waiting checklist
    labeled:
      issue:
        body: |
          :wave: Hello,
          Please follow the steps in the issue template for self-check, and then tell us the result of your operation, which will help us to help you solve the problem.

          :wave: æ‚¨å¥½ï¼Œ
          è¯·æŒ‰ç…§æ¨¡æ¿ä¸­çš„æ“ä½œæ­¥éª¤è¿›è¡Œè‡ªæ£€ï¼Œç„¶åå‘Šè¯‰æˆ‘ä»¬æ‚¨çš„æ“ä½œç»“æœï¼Œè¿™å°†æœ‰åŠ©äºæˆ‘ä»¬ååŠ©æ‚¨è§£å†³é—®é¢˜ã€‚

  # éœ€è¦æ›´å¤šä¿¡æ¯
  - name: need more info
    labeled:
      issue:
        body: |
          :wave: Hello,
          We need more information to make suggestions. Please edit your issue again, complete the information requested in the template, and describe your issue in as much detail as possible.

          :wave: æ‚¨å¥½ï¼Œ
          æˆ‘ä»¬éœ€è¦æ›´å¤šä¿¡æ¯æ‰èƒ½ç»™å‡ºå»ºè®®ï¼Œè¯·é‡æ–°ç¼–è¾‘æ‚¨çš„ issue ï¼Œå®Œå–„æ¨¡æ¿ä¸­è¦æ±‚æä¾›çš„ä¿¡æ¯ï¼Œå¹¶å°½å¯èƒ½è¯¦ç»†åœ°æè¿°æ‚¨çš„é—®é¢˜ã€‚

  # è¯·æè¿°è¯¦ç»†ä¸€ç‚¹
  - name: describe in detail
    labeled:
      issue:
        body: |
          :wave: Hello,
          Please describe your problem in as much detail as possible. If you donâ€™t know how to describe the problem in detail, this article can help you: [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html).

          :wave: æ‚¨å¥½ï¼Œ
          è¯·å°½å¯èƒ½è¯¦ç»†åœ°æè¿°æ‚¨çš„é—®é¢˜ã€‚å¦‚æœä¸çŸ¥é“å¦‚ä½•è¯¦ç»†åœ°æè¿°é—®é¢˜ï¼Œè¿™ä»½æ•™ç¨‹å¯ä»¥å¸®åŠ©åˆ°æ‚¨ï¼š[æé—®çš„æ™ºæ…§](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md) ã€‚

  # æ–‡æ¡£ä¸­æœ‰ç­”æ¡ˆ
  - name: read docs
    labeled:
      issue:
        body: |
          :wave: Hello,
          Your question is answered in the official documents of [Volantis](https://volantis.js.org) and [Hexo](https://hexo.io), if you canâ€™t find it, you can try to search.

          :wave: æ‚¨å¥½ï¼Œ
          æ‚¨çš„ç–‘é—®åœ¨ [Volantis](https://volantis.js.org) å’Œ [Hexo](https://hexo.io) çš„å®˜æ–¹æ–‡æ¡£æœ‰ç­”æ¡ˆï¼Œå¦‚æœæ‰¾ä¸åˆ°å¯ä»¥å°è¯•è¿›è¡Œæœç´¢ã€‚

  # é‡‡çº³çš„å»ºè®®
  - name: todo
    labeled:
      issue:
        body: |
          :wave: Hello,
          Your suggestion is great, we will add this feature in subsequent versions, thank you very much!

          :wave: æ‚¨å¥½ï¼Œ
          æ‚¨çš„å»ºè®®å¾ˆæ£’ï¼Œæˆ‘ä»¬å°†ä¼šåœ¨åç»­ç‰ˆæœ¬ä¸­åŠ å…¥è¿™ä¸ªåŠŸèƒ½ï¼Œéå¸¸æ„Ÿè°¢ï¼

  # è¿Ÿè¿Ÿæ²¡æœ‰å›å¤
  - name: waiting response
    labeled:
      issue:
        body: |
          :wave: Hello,
          Are you still there? We are waiting for your response. If you do not reply, we will close this issue.

          :wave: æ‚¨å¥½ï¼Œ
          è¿˜åœ¨å—ï¼Ÿæˆ‘ä»¬æ­£ç­‰å¾…æ‚¨çš„å›åº”ï¼Œå¦‚æœæ‚¨è¿Ÿè¿Ÿæ²¡æœ‰å›å¤ï¼Œæˆ‘ä»¬å°†ä¼šå…³é—­è¿™ä¸ª issue ã€‚

  ################ å…³é—­ ################
  # é‡å¤çš„é—®é¢˜
  - name: duplicate
    labeled:
      issue:
        body: |
          :wave: Hello,
          This is a duplicate issue, but we still appreciate your feedback.

          :wave: æ‚¨å¥½ï¼Œ
          è¿™æ˜¯ä¸€ä¸ªé‡å¤çš„é—®é¢˜ï¼Œä½†æˆ‘ä»¬ä»ç„¶æ„Ÿè°¢æ‚¨çš„åé¦ˆã€‚
        action: close

  # ä¸äºˆä¿®å¤
  - name: wontfix
    labeled:
      issue:
        body: |
          :wave: Hello,
          Due to the design or external issues, we will not deal with this, but we still appreciate your feedback.

          :wave: æ‚¨å¥½ï¼Œ
          ç”±äºè®¾è®¡å¦‚æ­¤ï¼Œæˆ–è€…æ˜¯å¤–ç•Œé—®é¢˜å¯¼è‡´ï¼Œæˆ‘ä»¬ä¸ä¼šå¯¹æ­¤è¿›è¡Œå¤„ç†ï¼Œä½†ä»ç„¶æ„Ÿè°¢æ‚¨çš„åé¦ˆï¼
        action: close

  # ç”±äºæ²¡æœ‰å›å¤è€Œè¢«å…³é—­
  - name: losing contact
    labeled:
      issue:
        body: |
          :wave: Hello,
          Due to your delay in replying, we closed this issue.

          :wave: æ‚¨å¥½ï¼Œ
          ç”±äºæ‚¨è¿Ÿè¿Ÿæ²¡æœ‰å›å¤ï¼Œæˆ‘ä»¬å…³é—­äº†è¿™ä¸ª issue ã€‚
        action: close

  # é—®é¢˜å¾—ä»¥è§£å†³
  - name: resolved
    labeled:
      issue:
        body: |
          :wave: Hello,
          This issue has been marked as resolved. If there are other issues, please contact us with a new issue.

          :wave: æ‚¨å¥½ï¼Œ
          æ­¤ issue å·²ç»è¢«æ ‡è®°ä¸ºå·²è§£å†³ï¼Œå¦‚æœè¿˜æœ‰å…¶å®ƒé—®é¢˜ï¼Œè¯·æå‡ºæ–°çš„ issue è”ç³»æˆ‘ä»¬ã€‚
        action: close

  # BUGå¾—ä»¥ä¿®å¤
  - name: fixed
    labeled:
      issue:
        body: |
          :wave: Hello,
          This bug has been fixed, please update your volantis.

          :wave: æ‚¨å¥½ï¼Œ
          æ­¤ BUG å·²ç»è¢«ä¿®å¤ï¼Œè¯·æ›´æ–°æ‚¨çš„ Volantis ç‰ˆæœ¬ã€‚
        action: close

  # Not following issue template
  - name: ğŸ™ Not following issue template
    labeled:
      issue:
        body: |
          :wave: Hello,
          This issue is being automatically closed because it does not follow the issue template.

          :wave: æ‚¨å¥½ï¼Œ
          å› ä¸ºæ‚¨æ²¡æœ‰æŒ‰ç…§æ¨¡æ¿ä¸­çš„æ“ä½œæ­¥éª¤è¿›è¡Œè‡ªæ£€ï¼Œè¿™ä¸ªissueå°†è¢«è‡ªåŠ¨å…³é—­ã€‚
        action: close