#####################################
##      Material X                 ##
##      version: 1.0 beta2         ##
##      updated: 2018-11-25        ##
#####################################

# >> ä¸»é¢˜é…ç½®å†™æ³•ç¤ºä¾‹ ---------------------------------------------------------------------
# âš ï¸ æ³¨æ„ï¼šè¿™é‡Œçš„å†…å®¹éœ€è¦å¤åˆ¶åˆ°ä¸»ç›®å½•åˆ°configä¸­æ‰æœ‰æ•ˆï¼Œå†™åœ¨è¿™é‡Œæ˜¯ä¸ºäº†æä¾›å‚è€ƒ

# å¯¼èˆªæ ï¼Œurlå¿…é¡»ä»¥ "/" ç»“å°¾
nav_menu:
  - name: ä¸»é¡µ
    icon: fas fa-home
    url: https://xaoxuu.com/
  - name: é¡¹ç›®
    icon: fas fa-flask
    url: https://xaoxuu.com/projects/
  - name: åšå®¢
    icon: fas fa-rss
    url: /
  - name: å½’æ¡£
    icon: fas fa-archive
    url: archives/
  - name: å…³äº
    icon: fas fa-user
    url: https://xaoxuu.com/about/

# å…¬å‘Šçš„å†™æ³•ç¤ºä¾‹ï¼Œè¿™åªæ˜¯ä¸ªä¾‹å­å“¦ï¼Œéœ€è¦æ˜¾ç¤ºå…¬å‘Šçš„æ—¶å€™å†™åœ¨ä¸»ç›®å½•çš„configä¸­ï¼Œä¸éœ€è¦çš„æ—¶å€™æ³¨é‡Šæ‰å°±å¯ä»¥ï¼Œå¦‚æœä½ ååˆ†å–œæ¬¢è¿™ä¸ªä¸»é¢˜ï¼Œå¯ä»¥æŠŠè¿™ä¸ªå…¬å‘Šcopyåˆ°ä½ é‚£é‡ŒğŸ˜„
announcement: 'æœ¬ç«™ä½¿ç”¨ <b><a href="https://xaoxuu.com/wiki/material-x/">Material X</a></b> ä½œä¸ºä¸»é¢˜ï¼Œå–œæ¬¢è¿™ä¸ªä¸»é¢˜çš„æœ‹å‹å¯ä»¥é˜…è¯»æ–‡æ¡£è¿›è¡Œå®‰è£…å“¦ã€‚'

# å‹é“¾çš„å†™æ³•ç¤ºä¾‹
links:
- name: xaoxuu's blog
  avatar: https://xaoxuu.com/assets/img/avatar.jpg
  url: https://xaoxuu.com/blog

# é¡µè„šç¤¾äº¤ä¿¡æ¯çš„å†™æ³•ç¤ºä¾‹
social:
  - icon: fas fa-envelope
    url: mailto:me@xaoxuu.com
  - icon: fab fa-github
    url: https://github.com/xaoxuu
  - icon: fas fa-music
    url: https://music.163.com/#/user/home?id=63035382

# åšä¸»ä¿¡æ¯çš„å†™æ³•ç¤ºä¾‹
avatar: https://xaoxuu.com/assets/img/avatar.jpg
title: åšå®¢åç§°
motto: è¿™æ˜¯æˆ‘çš„åº§å³é“­


# >> ä¸»é¢˜é…ç½® ---------------------------------------------------------------------
# âœ… è¿™é‡Œçš„å†…å®¹ç›´æ¥åœ¨ä¸‹é¢è¿›è¡Œä¿®æ”¹

# å­—ä½“ åœ¨è¿™é‡Œé€‰å¥½ä½ éœ€è¦çš„å­—ä½“ï¼šhttps://fonts.google.comï¼Œç„¶ååœ¨_defines.lessä¸­ä¿®æ”¹font_familyã€‚
google_fonts: 'Ubuntu|Ubuntu+Mono' # å¤šä¸ªå­—ä½“ä¸­é—´ç”¨è‹±æ–‡ç«–çº¿éš”å¼€

# style: material    # å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ä¸»é¢˜è‰²
style: pure        # å¯¼èˆªæ å’Œæ ‡é¢˜æ èƒŒæ™¯æ˜¯ç™½è‰²


# å³è¾¹çš„å°çª—å£ï¼Œä¸æƒ³æ˜¾ç¤ºå“ªä¸€é¡¹çš„æŠŠenableè®¾ç½®ä¸ºfalseå³å¯
widgets:
  # åšä¸»ä¿¡æ¯åŒºï¼Œæ˜¯å¦æ˜¾ç¤ºä¸ªäººå¤´åƒã€æ ¼è¨€ã€ç¤¾äº¤ä¿¡æ¯ç­‰
  author:
    enable: true
    avatar: true # æ˜¯å¦æ˜¾ç¤ºå¤´åƒï¼Œå¦‚æœæ˜¯ï¼Œéœ€è¦åœ¨ä¸»ç›®å½•çš„configä¸­å†™avatarçš„URL
    title: false # æ˜¯å¦æ˜¾ç¤ºåšå®¢åã€å¤´è¡”ç­‰ç­‰ã€‚å¦‚æœæ˜¯ï¼Œéœ€è¦åœ¨ä¸»ç›®å½•çš„configä¸­å†™title
    motto: false # æ˜¯å¦æ˜¾ç¤ºæ ¼è¨€åº§å³é“­ç­‰ç­‰ã€‚å¦‚æœæ˜¯ï¼Œéœ€è¦åœ¨ä¸»ç›®å½•çš„configä¸­å†™motto
    social: true # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤ä¿¡æ¯ï¼ˆå†…å®¹åŒé¡µè„šçš„ç¤¾äº¤ä¿¡æ¯ï¼‰å¦‚æœæ˜¯ï¼Œéœ€è¦åœ¨ä¸»ç›®å½•çš„configä¸­å†™socialï¼Œæ”¯æŒiconå’ŒURL
  # å…¬å‘Šï¼Œå†…å®¹å†™åœ¨ä¸»ç›®å½•çš„configä¸­
  announcement:
    enable: true
    icon: fas fa-bullhorn
    title: "å…¬å‘Š"
  # æ˜¾ç¤ºæ–‡ç« åˆ†ç±»
  categories:
    enable: true
    icon: fas fa-folder-open
    title: "åˆ†ç±»"
  # æ˜¾ç¤ºæ–‡ç« æ ‡ç­¾
  tagcloud:
    enable: true
    icon: fas fa-tags
    title: "æ ‡ç­¾"
  # æ˜¾ç¤ºç½‘æ˜“äº‘æ­Œå•
  music:
    enable: true
    icon: fas fa-headphones-alt
    title: "éŸ³ä¹"
    playlist_id: 746319661 # æ­Œå•id
  # æ˜¾ç¤ºå‹é“¾ï¼Œå‹é“¾çš„å†…å®¹å†™åœ¨ä¸»ç›®å½•çš„configä¸­
  links:
    enable: true
    icon: fas fa-handshake
    title: "å‹é“¾"
    mailto: "me@xaoxuu.com" # å³è¾¹æ˜¾ç¤ºâ• ï¼Œç‚¹å‡»ç»™è¿™ä¸ªåœ°å€å‘é€é‚®ä»¶æ·»åŠ å‹é“¾
  # æ˜¾ç¤ºç›®å½•ï¼ˆåœ¨æ–‡ç« ä¸­è®¾ç½®toc:falseå¯ä»¥éšè—å•ç¯‡æ–‡ç« çš„ç›®å½•ï¼‰
  toc:
    enable: true
    icon: fas fa-list
    title: "ç›®å½•"


# æ¨èæ–‡ç« 
recommended_posts:
  autoDisplay: false # è‡ªåŠ¨åœ¨æ–‡ç« åº•éƒ¨æ˜¾ç¤ºæ¨èæ–‡ç« ï¼Œå¦‚æœä½ ä½¿ç”¨Material-Xä¸»é¢˜ï¼Œè¿™é‡Œè¦è®¾ç½®ä¸ºfalseã€‚
  server: https://api.truelaurel.com # åç«¯æ¨èæœåŠ¡å™¨åœ°å€
  timeoutInMillis: 10000 # æœåŠ¡æ—¶é•¿ï¼Œè¶…è¿‡æ­¤æ—¶é•¿ï¼Œåˆ™ä½¿ç”¨ç¦»çº¿æ¨èæ¨¡å¼
  excludePattern: []
  titleHtml: <h4>æ¨èæ–‡ç« </h4> #è‡ªå®šä¹‰æ ‡é¢˜
  internalLinks: 3 # å†…éƒ¨æ–‡ç« æ•°é‡
  externalLinks: 2 # å¤–éƒ¨æ–‡ç« æ•°é‡
  fixedNumber: false


# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
