##########################################################################
############################## 主题基本信息 ################################
theme_info:
  name: Material X
  version: 1.0-beta11
  docs: https://xaoxuu.com/wiki/material-x/
  # 主题的CDN地址，如果你的源码托管到国内CDN可以更改此链接。如需启用CDN，请在主目录的config中设置import，详见文档。
  cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@18.12.36/
##########################################################################
# 请务必阅读官方文档！！！
# 请务必阅读官方文档！！！
# 请务必阅读官方文档！！！


# style: material    # 导航栏和标题栏背景是主题色
style: pure        # 导航栏和标题栏背景是白色

# 这里的widgets字段是对widget的默认设置，如需修改请参照文档在主目录的config中写。
widgets:
  # 文章分类的默认配置
  category:
    icon: fas fa-folder-open
    title: "博文分类"
  # 文章标签的默认配置
  tagcloud:
    icon: fas fa-fire
    title: "热门话题"
  # 文章目录的默认配置
  toc:
    icon: fas fa-list
    title: "目录"
  # 音乐控件的默认配置
  music:
    display:           # 批量控制哪一类页面显示
      home: false      # 在主页是否显示
      tag: false       # 在标签页面是否显示
      category: false  # 在分类页面是否显示
      archive: false   # 在归档页面是否显示
      page: false      # layout: page 的页面是否显示
      links: true      # layout: links 的页面是否显示
      post: true       # layout: post 的页面是否显示


# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false


# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
