############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.4.6/


############################### 主题样式 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
# 服务开关，如果你想禁用某些功能，直接设置为false或者注释掉，相关的js脚本就不会加载。
# 有些服务这里打开了也未必会生效，还需要额外的配置，详见文档。
services:
  cdn: true
  scrollreveal: true
  nodewaves: true
  busuanzi: true
  # fastclick: true
  # popular_posts: true   # 需要安装插件  hexo-related-popular-posts
  comments: true
  volantis: true
  # music: true
  # share: true
  # qrcode: true    # 需要安装插件  npm i -S hexo-helper-qrcode


############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
loading_img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png



############################### 自定义 ###############################

# 主页封面
home_cover:
  title: "xaoxuu"
  # logo: assets/logo.png
  search_placeholder: ' '
  # 主页封面菜单
  menu:
    - name: 近期文章
      icon: fas fa-clock
      url: '#posts'
    - name: 应用程序
      icon: fas fa-cube
      url: wiki/
    - name: 归档
      icon: fas fa-archive
      url: blog/archives/
    - name: 关于
      icon: fas fa-info-circle
      url: about/

# 桌面端导航栏菜单
menu:
  - name: Cocoa Dev
    icon: fab fa-apple
    url: blog/categories/cocoa-dev/
  - name: Dev
    icon: fas fa-laptop-code
    url: blog/categories/dev/
  - name: Life
    icon: fas fa-coffee
    url: blog/categories/life/

# 手机端导航菜单（从右上角的按钮点击展开）
menu_m:
  - name: 近期文章
    icon: fas fa-clock
    url: /
  - name: 文章归档
    icon: fas fa-archive
    url: blog/archives/
  - name: 开源项目
    icon: fas fa-flask
    url: wiki/
  - name: 歌单分享
    icon: fas fa-compact-disc
    url: music/
  - name: 我的友链
    icon: fas fa-link
    url: friends/
  - name: 关于小站
    icon: fas fa-info-circle
    url: about/


# 侧边栏小部件
sidebar:
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png
    social: true
  - widget: toc
  - widget: list
    icon: fas fa-map-signs
    title: 站内导航
    rows:
      - name: 开源项目
        icon: fas fa-flask
        url: wiki/
      - name: 文章归档
        icon: fas fa-archive
        url: blog/archives/
      - name: 歌单分享
        icon: fas fa-compact-disc
        url: music/
      - name: 我的友链
        icon: fas fa-link
        url: friends/
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: blog/categories/
  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: blog/tags/
  - widget: related_posts
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/user/home?id=63035382
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2615636388     # 歌曲/专辑/歌单 ID

# 社交信息
social:
  - icon: fas fa-rss
    url: atom.xml
  - icon: fas fa-envelope
    url: mailto:me@xaoxuu.com
  - icon: fab fa-github
    url: https://github.com/xaoxuu
  - icon: fas fa-headphones-alt
    url: https://music.163.com/#/user/home?id=63035382

# 分享按钮
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  - id: qrcode
    name: 微信
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  - id: qrcode
    name: QRcode
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



# footer: 页脚文字，支持markdown


############################### 评论 ###############################
# disqus_shortname: xaoxuu
# livere_uid:
# valine
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 20 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
  highlight: false





############################### 杂项，请勿删除 ###############################
# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
