name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
  watch:
    types: started
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: DeMoorJasper/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          :wave: Hello,
          This issue has been automatically marked as stale because lack of recent activity. 
          It will be closed if no further activity occurs. 
          Thank you for your contributions. 
        days-before-stale: 30
        days-before-close: 1
        stale-issue-label: 'no-activity'
        exempt-issue-label: 'adopted suggestion,bug,debugging,waiting response,todo'
